version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: ./Dockerfile-mongo
      args:
        - DB_USERNAME=root
        - DB_PASSWORD=secret
        - DB_DATABASE=orders_worker
    networks:
      - app-network

  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile-workspace
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
