version: '3'

services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile-workspace
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge