version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: ./Dockerfile-mongo
      args:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./Dockerfile-app
      args:
        DB_HOST: mongo
        DB_PORT: ${DB_PORT}
        APP_PORT: ${APP_PORT}
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
