FROM node:12
ARG DB_HOST
ARG DB_PORT
ARG APP_PORT
COPY package*.json /app/
WORKDIR /app
RUN npm install --production
COPY . .
RUN cp .env.example .env && sed -i 's/DB_HOST=.*/DB_HOST=${DB_HOST}/' .env
EXPOSE ${APP_PORT}
CMD ["npm", "start"]